<a href="https://colab.research.google.com/github/azarcoder/pytorch_udemy/blob/main/PyTorch_intro_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Pytroch
- developed by facebook
- > nvidia-smi - check CUDA in cmd
- In PyTorch, a tensor is the basic building block—like a NumPy array, but with additional features that make it powerful for deep learning.

| Rank | Tensor Type       | Example                                |
|------|--------------------|----------------------------------------|
| 0    | Scalar             | `torch.tensor(5)`                      |
| 1    | Vector             | `torch.tensor([1, 2, 3])`              |
| 2    | Matrix             | `torch.tensor([[1, 2], [3, 4]])`       |
| 3+   | Higher-dim Tensor  | `torch.randn(3, 3, 28, 28)` (e.g. images) |




In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True


## Creating tensors

In [ ]:
# 1. Scalar tensor 0D - single dimention tensor called scaler
# Tensor represents data in pytorch.

scalar = torch.tensor(42)
print("Scalar tensor : ", scalar)
print("Scalar Dimension : ", scalar.ndim)
print("Shape of Scalar tensor : ", scalar.shape)

Scalar tensor :  tensor(42)
Scalar Dimension :  0
Shape of Scalar tensor :  torch.Size([])


## creating 1D teonsor (Vector)


In [ ]:
# 1D tensor : Vector

vector = torch.tensor([1,2,3])
print("vector tensor : ", vector)
print("vector Dimension : ", vector.ndim)
print("Shape of vector tensor : ", vector.shape)

vector tensor :  tensor([1, 2, 3])
vector Dimension :  1
Shape of vector tensor :  torch.Size([3])


## Careating 2D - (matrix)

In [ ]:
# matrix 2D
matrix = torch.tensor([[1,2], [3,4]])
print("matrix tensor : ", matrix)
print("matrix Dimension : ", matrix.ndim)
print("Shape of matrix tensor : ", matrix.shape)

matrix tensor :  tensor([[1, 2],
        [3, 4]])
matrix Dimension :  2
Shape of matrix tensor :  torch.Size([2, 2])


## 3 Dimentional (Tensors)

In [ ]:
# 3D tensor
tensor3d = torch.tensor([
                      [[1,2], [3,4]],
                      [[1,2], [3,4]]
                      ])
print("tensor3d tensor : ", tensor3d)
print("tensor3d Dimension : ", tensor3d.ndim)
print("Shape of tensor3d tensor : ", tensor3d.shape)

tensor3d tensor :  tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])
tensor3d Dimension :  3
Shape of tensor3d tensor :  torch.Size([2, 2, 2])


In [ ]:
# GPU acceleration

if torch.cuda.is_available():
  gpu_tensor = vector.to('cuda')
  print("Tensor on GPU: ", gpu_tensor)
else:
  print("CUDA is not available on this machine.")

Tensor on GPU:  tensor([1, 2, 3], device='cuda:0')


In [ ]:
# Tensor properties

print("Data type of matrix :", matrix.dtype)

print("Device of Tensor : ", matrix.device)
print("Device of Tensor : ", gpu_tensor.device)

print("Is tensor on CUDA : ", matrix.is_cuda)
print("Is tensor on CUDA : ", gpu_tensor.is_cuda)

print("Size: ", matrix.size())
print("Number of elements : ", matrix.numel())

Data type of matrix : torch.int64
Device of Tensor :  cpu
Device of Tensor :  cuda:0
Is tensor on CUDA :  False
Is tensor on CUDA :  True
Size:  torch.Size([2, 2])
Number of elements :  4


In [ ]:
!nvidia-smi

Fri Apr 18 04:40:04 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   49C    P0             30W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Indexing Tensors  and slicing

In [ ]:
# accessing

tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [70, 80, 90]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

print('-'*20)
print("accessing")
print(tensor[0])
print(tensor[0,2])
print(tensor[1,2])
print(tensor[2,2])
print('-'*20)
print("slicing")
print(tensor[:, 1])
print(tensor[1:, 1:])
print(tensor[:2, :2])

# Fancy indexing
# (0,1) --> 20
# (2,2) --> 90
selected_elements = tensor[[0,2],[1,2]] #[0,1][2,2]
print(selected_elements)

print('-'*20)
mask = tensor > 50 #elements grater than 50 is True
print(mask)
print(tensor[mask])

#chnaging values

tensor[:,0] = torch.tensor([100, 200, 300]) #1st column change
print(tensor)

indices = torch.tensor([0,2])
selected_rows = torch.index_select(tensor,dim=1,index=indices)
print(selected_rows)

print(tensor[:, ::2]) #selecting column step 2
# print(tensor[::-1]) it doen't work in pytorch
torch.flip(tensor, dims=[0]) #flip rows

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [70, 80, 90]])
2
torch.Size([3, 3])
--------------------
accessing
tensor([1, 2, 3])
tensor(3)
tensor(6)
tensor(90)
--------------------
slicing
tensor([ 2,  5, 80])
tensor([[ 5,  6],
        [80, 90]])
tensor([[1, 2],
        [4, 5]])
tensor([ 2, 90])
--------------------
tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])
tensor([70, 80, 90])
tensor([[100,   2,   3],
        [200,   5,   6],
        [300,  80,  90]])
tensor([[100,   3],
        [200,   6],
        [300,  90]])
tensor([[100,   3],
        [200,   6],
        [300,  90]])


tensor([[300,  80,  90],
        [200,   5,   6],
        [100,   2,   3]])