<a href="https://colab.research.google.com/github/azarcoder/pytorch_udemy/blob/main/Tensor_DataTypes_and_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# data types for tensors
'''
* floating -- for most deep learning tasks ---> float32, float64, float16
* integers - for categorical data and indices --> int32, int64, int8
* booleans - mask or logical operation
* Complex number - advanced computation --> complex64, complex128

memory consumption : float16 << float32 << float64
computation : lower precision will be faster on gpu
numberical precision : float64 is more precise than float32'''


- float32 --> default for most NN models
- float64 --> high precision computation
- int32 --> general purpose integer
- int64 --> tensor indices
- int8, int16 --> reduce memory usage
- bool --> mask and logical operation
- float16 --> half precision of your default floating dtype, reduce memory usage
- complex64 --> advanced computation

In [1]:
import torch

In [3]:
float32_tensor = torch.ones(1000, dtype=torch.float32)
float64_tensor = torch.ones(1000, dtype=torch.float64)

# tensor.element_size()
# element_size() --> gives you the size of one element in bytes
# nelement() --> gives the total number of elements in tensor

print(float32_tensor.element_size())
print(float32_tensor.nelement())

print(float64_tensor.element_size())
print(float64_tensor.nelement())

print("Memory used by float32 tensor : ", float32_tensor.element_size() * float32_tensor.nelement(), " bytes")
print("Memory used by float64 tensor : ", float64_tensor.element_size() * float64_tensor.nelement(), " bytes")

4
1000
8
1000
Memory used by float32 tensor :  4000  bytes
Memory used by float64 tensor :  8000  bytes


# Tensor Manipulation
 - reshaping
 - slicing
 - joing and splitting
 - transposing and permuting dimention


In [7]:
import torch

# Reshaping

In [12]:
ogt = torch.arange(12)
print(ogt)
print(ogt.nelement())
print(ogt.shape)
print(ogt.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
torch.Size([12])
1


In [18]:
#1d to 2d
# reshape() works on both contiguous and non-contiguous tensors
#create new copy
mt = ogt.reshape(3,-1 )
print(mt)
print(mt.ndim)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2


In [29]:
print(ogt.is_contiguous())
# view() does not copy data, it just gives a new “view” on the same memory.
# view() works only on contiguous tensors.
ogt.view(2,-1) #-1 means automatically ndim

True


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

#Slicing

In [37]:
t = torch.arange(1,10).reshape(3,3)
print(t)
'''
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
'''
print(t[0])
t[:,2]
t[1:, 1:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])


tensor([[5, 6],
        [8, 9]])

# Joining

In [40]:
#torch.cat() -->merge tensors along an existing dimention

t1 = torch.tensor([[1,2], [3,4]])
t2 = torch.tensor([[5,6], [7,8]])
j = torch.cat((t1, t2), dim=0) #0 means row 1 means col
print(j)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


# stacking

In [51]:
#stack --> created a new dimention, increses the tensor's rank
t1 = torch.tensor([[1,2], [3,4]])
t2 = torch.tensor([[5,6], [7,8]])

s = torch.stack((t1, t2), dim=0)
s2 = torch.stack((t1, t2), dim=1)
print(s)
print(s2)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


# Splitting
 - > torch.chunck() - divides your tensor into equal-sized chunks
 - > torch.split() - allows uneven splitting based on size

In [69]:
#torch.chuck()
print('chunk:')
t = torch.arange(12)
x = torch.chunk(t, 5, dim = 0)

for i in x:
  print(i)

print('-'*30)
print('split:')
x = torch.split(t, 5, dim = 0)

for i in x:
  print(i)

chunk:
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])
------------------------------
split:
tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11])


# Transporsing and Permuting
- > transpose() - swaps two dimentions mxn --> nmx
- > premute() - rearranges all dimention in the specified order


In [74]:
t = torch.arange(24).reshape(3, -1)
print(t)
tp = t.transpose(0, 1)
print(tp)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  8, 16],
        [ 1,  9, 17],
        [ 2, 10, 18],
        [ 3, 11, 19],
        [ 4, 12, 20],
        [ 5, 13, 21],
        [ 6, 14, 22],
        [ 7, 15, 23]])


In [78]:
# x[batch][channel][width]
x = torch.tensor([
  [ [1, 2],     # x[0][0] → batch 0, channel 0
    [3, 4] ],   # x[0][1] → batch 0, channel 1

  [ [5, 6],     # x[1][0] → batch 1, channel 0
    [7, 8] ]    # x[1][1] → batch 1, channel 1
])

'''
So now, instead of:

batch first,

then channel,

then width,

We are saying:

width first,

then batch,

then channel
'''
print(x)
print(x.ndim)
x = x.permute(2, 0, 1) #New shape will be (width, batch, channel)
print(x)


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
tensor([[[1, 3],
         [5, 7]],

        [[2, 4],
         [6, 8]]])


# Matrix Aggregation

In [86]:
t = torch.arange(9, dtype=float).reshape(3, -1)
print(t)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)


In [87]:
print(t.sum())
print(t.min())
print(t.max())
print(t.median())
print(t.mode())
print(t.mean())

tensor(36., dtype=torch.float64)
tensor(0., dtype=torch.float64)
tensor(8., dtype=torch.float64)
tensor(4., dtype=torch.float64)
torch.return_types.mode(
values=tensor([0., 3., 6.], dtype=torch.float64),
indices=tensor([0, 0, 0]))
tensor(4., dtype=torch.float64)


In [90]:
#dim=0 --> rows
#dim=1 --> column

print(t.sum(dim=0)) #row wise sum
print(t.sum(dim=1)) #column wise sum

tensor([ 9., 12., 15.], dtype=torch.float64)
tensor([ 3., 12., 21.], dtype=torch.float64)


In [92]:
cumulatice_sum = t.cumsum(dim=1)
print(cumulatice_sum)

cumulatice_prod = t.cumprod(dim=1)
print(cumulatice_prod)

tensor([[ 0.,  1.,  3.],
        [ 3.,  7., 12.],
        [ 6., 13., 21.]], dtype=torch.float64)
tensor([[  0.,   0.,   0.],
        [  3.,  12.,  60.],
        [  6.,  42., 336.]], dtype=torch.float64)


In [95]:
#masked

masked_matrix_sum = t[t > 5]
print(masked_matrix_sum)

tensor([6., 7., 8.], dtype=torch.float64)


# Normalize matrix

In [97]:
print(t)
mxv = t.max()
mxm = t.min()
norm_t = (t - mxm) / (mxv - mxm) #formula
print(norm_t)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)
tensor([[0.0000, 0.1250, 0.2500],
        [0.3750, 0.5000, 0.6250],
        [0.7500, 0.8750, 1.0000]], dtype=torch.float64)
